services:
  - type: web
    name: tu-proyecto
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run interfaz.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true